import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home({ data }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        {data.map((ev) => (
          <Link href={`/events/${ev.id}`}>
            <img src={ev.image} width={300} height={300} alt={ev.title} />
            <h2>{ev.title}</h2>
            <p>{ev.description}</p>
          </Link>
        ))}
      </main>
      <footer className={styles.footer}></footer>
    </>
  )
}

export async function getServerSideProps() {
  const { events_categories } = await import('/data/data.json')
  console.log(events_categories)
  return {
    props: {
      data: events_categories,
    },
  }
}
